// Package auth provides integration between the internal auth interface and the real DID authentication
package auth

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/agentries/amp-relay-go/pkg/auth"
)

// RealDIDAuthenticator wraps the pkg/auth Authenticator to implement the internal Authenticator interface
type RealDIDAuthenticator struct {
	didAuth       *auth.DIDAuthenticator
	serverDID     string
	serverPrivKey []byte
}

// NewRealDIDAuthenticator creates a new real DID authenticator
func NewRealDIDAuthenticator(resolver auth.DIDResolver, serverDID string, serverPrivKey []byte) *RealDIDAuthenticator {
	return &RealDIDAuthenticator{
		didAuth:       auth.NewDIDAuthenticator(resolver),
		serverDID:     serverDID,
		serverPrivKey: serverPrivKey,
	}
}

// Verify implements the internal Authenticator interface
func (r *RealDIDAuthenticator) Verify(ctx context.Context, did string, proof *AuthenticationProof) (*VerificationResult, error) {
	log.Printf("[RealDIDAuth] Verifying DID: %s", did)
	
	// Authenticate the DID using real DID resolution
	if err := r.didAuth.Authenticate(ctx, did); err != nil {
		return nil, &AuthError{
			Code:    ErrCodeAuthFailed,
			Message: fmt.Sprintf("DID authentication failed: %v", err),
		}
	}
	
	// For now, we'll generate a simple token after successful DID verification
	// In a full implementation, we'd verify the proof (signature, JWT, etc.)
	tokenID := generateTokenID()
	now := time.Now()
	expiresAt := now.Add(24 * time.Hour)
	
	return &VerificationResult{
		DID:        did,
		Token:      tokenID,
		ExpiresAt:  expiresAt,
		VerifiedAt: now,
		Claims: map[string]interface{}{
			"auth_method": "did_verification",
			"server_did":  r.serverDID,
		},
	}, nil
}

// ValidateToken validates a token
func (r *RealDIDAuthenticator) ValidateToken(ctx context.Context, token string) (*TokenClaims, error) {
	// For now, accept all tokens generated by this authenticator
	// In production, implement proper token validation
	return &TokenClaims{
		DID:       "validated_did",
		IssuedAt:  time.Now().Add(-1 * time.Hour),
		ExpiresAt: time.Now().Add(23 * time.Hour),
		TokenID:   token,
		Extra:     make(map[string]interface{}),
	}, nil
}

// RefreshToken refreshes a token
func (r *RealDIDAuthenticator) RefreshToken(ctx context.Context, token string) (string, error) {
	// Generate a new token
	newTokenID := generateTokenID()
	return newTokenID, nil
}

// RevokeToken revokes a token
func (r *RealDIDAuthenticator) RevokeToken(ctx context.Context, token string) error {
	// In a full implementation, add token to revocation list
	return nil
}

// GetServerDID returns the server's DID
func (r *RealDIDAuthenticator) GetServerDID() string {
	return r.serverDID
}

// DIDWebResolverFactory creates a DID web resolver for the relay server
func DIDWebResolverFactory(baseURL string) auth.DIDResolver {
	return auth.NewDIDWebResolver(baseURL)
}